In [1]:
import numpy as np

In [2]:
print("hello")

hello


In [3]:
myarr = np.array([1,2,3,4,5,6])

In [4]:
myarr

array([1, 2, 3, 4, 5, 6])

In [5]:
myarr = myarr.reshape(2,3)

In [6]:
myarr

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
myarr.ravel()

array([1, 2, 3, 4, 5, 6])

In [8]:
myarr = np.zeros(45)

In [9]:
myarr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
x = [[1,2,3], [4,5,6], [7,8,9]]

In [11]:
arr = np.array(x)

In [12]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr.sum(axis = 1) #column

array([ 6, 15, 24])

In [14]:
arr.sum(axis = 0) #row

array([12, 15, 18])

In [15]:
arr = np.array([[7,3,9],[1,3,2],[8,1,2]])

In [16]:
arr

array([[7, 3, 9],
       [1, 3, 2],
       [8, 1, 2]])

In [17]:
arr.argmin()

3

In [18]:
arr.argmax()

2

In [19]:
arr.argsort() #gives indexes of elements in ascending order 

array([[1, 0, 2],
       [0, 2, 1],
       [1, 2, 0]])

In [20]:
arr.argmin(axis = 0) #gives min in each col

array([1, 2, 1])

In [21]:
arr.argmin(axis = 1)

array([1, 0, 1])

In [48]:
arr = arr.ravel()

In [52]:
arr.reshape(9,1)

array([[7],
       [3],
       [9],
       [1],
       [3],
       [2],
       [8],
       [1],
       [2]])

In [54]:
np.where(arr > 5)

(array([0, 2, 6]),)

In [56]:
np.count_nonzero(arr)

9

In [58]:
np.nonzero(arr)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8]),)

In [66]:
def printSum(a,b):
    print(a + b)

In [68]:
printSum(2,4)

6
